"use client";

import { redirect } from "next/navigation";
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Medical Mushrooms market",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  const [isAuthenticated, setIsAuthenticated] = useState(null);

  useEffect(() => {
    const accessToken = localStorage.getItem("accessToken");
    const refreshToken = localStorage.getItem("refreshToken");
    const authenticated = !(accessToken === null || refreshToken === null);

    if (!authenticated) {
      redirect("/login");
    } else {
      setIsAuthenticated(authenticated);
    }
  }, [isAuthenticated]);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
