"use client";

import { redirect } from "next/navigation";
import { useEffect, useState } from "react";
import "../app/styles/global.css";

// export const metadata = {
//   title: "Medical Mushrooms market",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  const [isAuthenticated, setIsAuthenticated] = useState(null);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
